"""table

Revision ID: 9c5d3b9b23ae
Revises: 36d998185aef
Create Date: 2024-02-16 15:23:47.470261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5d3b9b23ae'
down_revision = '36d998185aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('total_price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('total_price')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
